Ensure source.json exists before committing updates
Added a check to ensure source.json exists before committing changes.

diff --git a/.github/workflows/update.yml b/.github/workflows/update.yml
--- a/.github/workflows/update.yml
+++ b/.github/workflows/update.yml
@@ -27,6 +27,13 @@ jobs:
       run: |
         git config --global user.name "github-actions[bot]"
         git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
-        git add source.json
-        git diff-index --quiet HEAD || git commit -m "Automated update of Stremio source metadata"
-        git push
+        
+        # Check if the file was created before running git commands
+        if [ -f "source.json" ]; then
+          git add source.json
+          git diff-index --quiet HEAD || git commit -m "Automated update of Stremio source metadata"
+          git push
+        else
+          echo "Error: source.json was not generated by the python script."
+          exit 1
+        fi
